version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    depends_on:
      - auth-mongo

  order-service:
    build: ./order-service
    ports:
      - "3002:3000"
    depends_on:
      - order-mongo

  auth-mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  order-mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - order_data:/data/db

volumes:
  auth_data:
  order_data:
